CREATE TABLE IF NOT EXISTS rol(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  descripcion VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS usuario (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  contrasena VARCHAR(255) NOT NULL,
  correo VARCHAR(100) NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  apellido_paterno VARCHAR(255) NOT NULL,
  apellido_materno VARCHAR(255),
  otp CHAR(4),
  estado SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  rol_id BIGINT NOT NULL,
  CONSTRAINT uk_usuario_correo UNIQUE(correo)
);

ALTER TABLE usuario
ADD CONSTRAINT fk_rol_usuario
FOREIGN KEY (rol_id)
REFERENCES rol(id)
ON DELETE RESTRICT;

CREATE TABLE IF NOT EXISTS plan(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  destino VARCHAR(255) NOT NULL,
  dias NUMERIC NOT NULL,
  ritmo VARCHAR(255) NOT NULL,
  url VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  estado SMALLINT NOT NULL DEFAULT 1,
  usuario_id BIGINT NOT NULL
);

ALTER TABLE plan
ADD CONSTRAINT fk_usuario_plan
FOREIGN KEY (usuario_id)
REFERENCES usuario(id)
ON DELETE RESTRICT;

CREATE TABLE IF NOT EXISTS lugar(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  direccion VARCHAR(255) NOT NULL,
  categoria VARCHAR(100) NOT NULL,
  plan_id BIGINT NOT NULL
);

ALTER TABLE lugar
ADD CONSTRAINT fk_plan_lugar
FOREIGN KEY (plan_id)
REFERENCES plan(id)
ON DELETE RESTRICT;

CREATE TABLE IF NOT EXISTS itinerario(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  dia NUMERIC NOT NULL,
  titulo VARCHAR(255) NOT NULL,
  resumen VARCHAR(500) NOT NULL,
  plan_id BIGINT NOT NULL
);

ALTER TABLE itinerario
ADD CONSTRAINT fk_plan_itinerario
FOREIGN KEY (plan_id)
REFERENCES plan(id)
ON DELETE RESTRICT;

CREATE TABLE IF NOT EXISTS actividad(
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  tiempo VARCHAR(100) NOT NULL,
  nombre VARCHAR(255) NOT NULL,
  nota VARCHAR(500) NOT NULL,
  itinerario_id BIGINT NOT NULL
);

ALTER TABLE actividad
ADD CONSTRAINT fk_itinerario_actividad
FOREIGN KEY (itinerario_id)
REFERENCES itinerario(id)
ON DELETE RESTRICT;

